name: Locale Audit

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: Tools
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Run audit
        run: npm run analyze

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: locale-workflow-report
          path: reports/workflow-report.md
          if-no-files-found: error

      - name: Publish job summary
        run: |
          {
            cat reports/workflow-report.md
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Commit changes (README.md, Locales/index.json)
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md Locales/index.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(locale): update README + Locales/index.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
